version: "3.7"

services:
  putt-stats-api-dev:
    container_name: putt-stats-api-dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/src
    ports:
      - 8081:8081
